# Generated by Django 4.2.5 on 2024-07-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_ability_type_pokemon_abilities_pokemon_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='attack',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='defense',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='evolutions',
            field=models.ManyToManyField(blank=True, related_name='pre_evolutions', to='pokemon.pokemon'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='hp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='special_attack',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='special_defense',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='speed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
